apiVersion: v1
kind: Service
metadata:
  name: prefect-server-service
  namespace: fraud-detection
spec:
  type: ClusterIP
  selector:
    app: prefect-server
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200