apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-worker-sa
  namespace: fraud-detection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-worker-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-worker-rolebinding
subjects:
  - kind: ServiceAccount
    name: prefect-worker-sa
    namespace: fraud-detection
roleRef:
  kind: ClusterRole
  name: prefect-worker-role
  apiGroup: rbac.authorization.k8s.io